name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/setup-gcloud@v0
      - uses: melvnl/melvnl@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
